### ISSUE TITLE
about use luci-app-ttyd from wan

### ISSUE THREAD

**Issue by wackejohn** [tano-systems/luci-app-ttyd#1]
Hello,
I want to use the luci-app-ttyd from wan (eg: from offcie access the router at home ), currently it need configure the firewall to open the port which ttyd listend....
Is there anyway that no need to open port on firewall to make the remote access of luci-app-ttyd working?thanks.

**Comment by namedun** [comment]
To access the ttyd service from wan it is necessary to open the port on the firewall. I don’t know any other way.
